services:
  app:
    build: .
    container_name: nextapp
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # сюда добавь свои переменные окружения:
      # - DATABASE_URL=...
      # - NEXTAUTH_URL=...
    networks:
      - web

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
