services:
  app:
    build: .
    container_name: nextapp
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # сюда добавь свои переменные окружения:
      # - DATABASE_URL=...
      # - NEXTAUTH_URL=...
    networks:
      - proxy
networks:
  proxy:
    external: true
